CC=gcc
#CFLAGS=-Wall -O2


BINDIR=../bin/cygwin
MKDIR=mkdir -p
FixPath=$1
CP=cp
CFLAGS=-DSINGLE_NETWORK


UTILDIR=$(BINDIR)/utils

EDAC40=edac40.h edac40.c
EDAC40MIRROR=mirror_edac40.h mirror_edac40.c

all : utils mirrors
utils : edac40list edac40sqwave
mirrors : mmdm_17tt mmdm_37ch mmdm_39ch_30mm mmdm_79ch_40mm mmdm_79ch_50mm  \
          piezo_19ch piezo_19lo_30 piezo_37ch piezo_37ch_trihex piezo_37ch_50mm piezo_37ch_50mm_2008 piezo_37ch_2005 piezo_79ch_50mm piezo_109ch_50mm piezo_lo18ch \
          mmdm_lin19ch piezo_lin20ch 

## ----------- utilities
edac40list : edac40list.c $(EDAC40)
	$(MKDIR) $(call FixPath,$(UTILDIR))
	$(CC) -o $(UTILDIR)/$@ $^ $(CFLAGS)

edac40sqwave : edac40sqwave.c $(EDAC40)
	$(MKDIR) $(call FixPath,$(UTILDIR))
	$(CC) -o $(UTILDIR)/$@ $^ $(CFLAGS)

# ----------- separate small diagnostic programs (to be build for some particular mirror model in corresponding subdirectories)

set_channel : set_channel.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

rotate : rotate.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

am_set : am_set.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

am_set2 : am_set2.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

random_test : random_test.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

print_pinout : print_pinout.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

19_set : 19_set.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

smiley37 : smiley37.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

circle : circle.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

5_set : 5_set.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

7_set : 7_set.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

degauss : degauss.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

ring1_set : ring1_set.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

ring2_set : ring2_set.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

pairs : pairs.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

smiley19 : smiley19.c $(EDAC40) $(EDAC40MIRROR)
	$(CC) -o $(OUTDIR)/$@ $^ -D$(DEFS) $(CFLAGS)

# ------------ mirror models
mmdm_17tt : OUTDIR=$(BINDIR)/mmdm_17tt
mmdm_17tt :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set am_set2 circle random_test print_pinout 5_set  OUTDIR=$(OUTDIR) DEFS=MMDM_17TT

mmdm_lin19ch : OUTDIR=$(BINDIR)/mmdm_lin19ch
mmdm_lin19ch :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set print_pinout OUTDIR=$(OUTDIR) DEFS=MMDM_LIN19CH

mmdm_37ch : OUTDIR=$(BINDIR)/mmdm_37ch
mmdm_37ch :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout 19_set smiley37 OUTDIR=$(OUTDIR) DEFS=MMDM_37CH

mmdm_39ch_30mm : OUTDIR=$(BINDIR)/mmdm_39ch_30mm
mmdm_39ch_30mm :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout ring1_set ring2_set OUTDIR=$(OUTDIR) DEFS=MMDM_39CH_30MM

mmdm_79ch_30mm : OUTDIR=$(BINDIR)/mmdm_79ch_30mm
mmdm_79ch_30mm :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(CP) sernum.ini $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout ring1_set ring2_set OUTDIR=$(OUTDIR) DEFS=MMDM_79CH_30MM

mmdm_79ch_40mm : OUTDIR=$(BINDIR)/mmdm_79ch_40mm
mmdm_79ch_40mm :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(CP) sernum.ini $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout ring1_set ring2_set OUTDIR=$(OUTDIR) DEFS=MMDM_79CH_40MM

mmdm_79ch_50mm : OUTDIR=$(BINDIR)/mmdm_79ch_50mm
mmdm_79ch_50mm :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(CP) sernum.ini $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout ring1_set ring2_set OUTDIR=$(OUTDIR) DEFS=MMDM_79CH_50MM

piezo_19ch : OUTDIR=$(BINDIR)/piezo_19ch
piezo_19ch :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout 7_set smiley19 degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_19CH

piezo_19lo_30 : OUTDIR=$(BINDIR)/piezo_19lo_30
piezo_19lo_30 :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_19LO_30

piezo_37ch : OUTDIR=$(BINDIR)/piezo_37ch
piezo_37ch :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout 19_set smiley37 degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_37CH

piezo_37ch_2005 : OUTDIR=$(BINDIR)/piezo_37ch_2005
piezo_37ch_2005 :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout 19_set smiley37 degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_37CH_2005	
	
piezo_37ch_trihex : OUTDIR=$(BINDIR)/piezo_37ch_trihex
piezo_37ch_trihex :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout 19_set smiley37 degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_37CH_TRIHEX
	
piezo_37ch_50mm : OUTDIR=$(BINDIR)/piezo_37ch_50mm
piezo_37ch_50mm :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout 19_set smiley19 smiley37 ring1_set ring2_set degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_37CH_50MM

piezo_37ch_50mm_2008 : OUTDIR=$(BINDIR)/piezo_37ch_50mm_2008
piezo_37ch_50mm_2008 :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout 19_set smiley37 degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_37CH_50MM_2008



piezo_79ch_50mm : OUTDIR=$(BINDIR)/piezo_79ch_50mm
piezo_79ch_50mm :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(CP) sernum.ini $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_79CH_50MM

piezo_109ch_50mm : OUTDIR=$(BINDIR)/piezo_109ch_50mm
piezo_109ch_50mm :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(CP) sernum.ini $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_109CH_50MM

piezo_lin20ch : OUTDIR=$(BINDIR)/piezo_lin20ch
piezo_lin20ch :
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout pairs degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_LIN20CH

piezo_lo18ch : OUTDIR=$(BINDIR)/piezo_lo18ch
piezo_lo18ch : 
	$(MKDIR) $(call FixPath,$(OUTDIR))
	$(MAKE) set_channel rotate am_set random_test print_pinout 7_set 19_set smiley19 smiley37 ring1_set ring2_set degauss OUTDIR=$(OUTDIR) DEFS=PIEZO_LO18CH
